### ISSUE TITLE
Handling of empty source directories

### ISSUE THREAD

**Issue by timothyryanwalsh** [timothyryanwalsh/brunnhilde#16]
Currently:

```
Traceback (most recent call last):
  File "/usr/local/bin/brunnhilde.py", line 579, in <module>
    main()
  File "/usr/local/bin/brunnhilde.py", line 557, in main
    process_content(args, source, cursor, conn, html, brunnhilde_version, siegfried_version)
  File "/usr/local/bin/brunnhilde.py", line 415, in process_content
    get_stats(args, source_dir, scan_started, cursor, html, brunnhilde_version, siegfried_version) # get aggregate stats and write to html file
  File "/usr/local/bin/brunnhilde.py", line 138, in get_stats
    begin_date = min(years, key=float)
ValueError: min() arg is an empty sequence
```

**Comment by timothyryanwalsh** [comment]
Fixed by commit https://github.com/timothyryanwalsh/brunnhilde/commit/e7d5ea6850c2662a0334732d54fda14b98fe1620
