### ISSUE TITLE
OSerror MAC 

### ISSUE THREAD

**Issue by oliviervd** [timothyryanwalsh/brunnhilde#44]
I can't seem to open brunnhilde. I keep getting this error: 

oliviervandhuynslager@mbp-van-olivier ~ % brunnhilde.py -z "/Users/oliviervandhuynslager/Desktop/foto's" /Users/oliviervandhuynslager/Desktop/test-1          
Traceback (most recent call last):
  File "/usr/local/bin/brunnhilde.py", line 898, in <module>
    main()
  File "/usr/local/bin/brunnhilde.py", line 649, in main
    siegfried_version = subprocess.check_output(["sf", "-version"]).decode()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by timothyryanwalsh** [comment]
Hi Olivier. From the output you've copied here, it looks like the issue is that Siegfried isn't installed on your system. See the [relevant section of the README](https://github.com/timothyryanwalsh/brunnhilde#core-requirements-all-operating-systems) for info on that.

If Siegfried is installed, it's possible that it's not on the system PATH. If that's the issue, the [Siegfried troubleshooting guide](https://github.com/richardlehane/siegfried/wiki/Getting-started#installing-the-latest-signature-file) might be helpful.
